import pokemon_openai

import flask
from flask import Flask, request, jsonify

app = flask.Flask(__name__)
app.config["DEBUG"] = True


@app.route('/monitoring', methods=['GET'])
def monitoring():
    """Endpoint for monitoring the status of the service.

    Returns:
        JSON: A JSON response indicating that the service is alive.
    """
    return jsonify({"message:": "I'm alive. :)"})


@app.route('/structured', methods=["POST"])
def structured_data():
    """Endpoint for processing structured data about Pokémon.

    This endpoint takes structured JSON data containing text describing a Pokémon and
     returns a response generated by the Pokemon OpenAI model.

    Returns:
        Structured JSON: A JSON response containing the generated structured response.
    """
    data = request.get_json()
    response = pokemon_openai.get_response_openai(data["text"])
    return jsonify(response)


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8080)
